import type { Metadata } from 'next'
import './globals.css'
import { Jost } from 'next/font/google'
import { Footer } from '@/components/Footer'

const jost = Jost({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'UOMO-Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        {children}
      </body>
    </html>
  )
}
